let &shell = 'pwsh' 
let &shellquote= ''
let &shellpipe= '| Tee-Object' 
let &shellxquote= ''
let &shellcmdflag='-NoLogo -NoProfile -ExecutionPolicy RemoteSigned -Command'
let &shellredir='| Out-File -Encoding UTF8'
