local maps = function(mode, key, action, desc)
  vim.keymap.set(mode, key, action, { silent = true, desc = desc })
end

local nmap = function (key, action, desc)
  maps('n', key, action, desc)
end

local imap = function (key, action, desc)
  maps('i', key, action, desc)
end

nmap('<A-e>', vim.diagnostic.open_float, "Open diagnostic float")
nmap('<A-q>', vim.diagnostic.setloclist, "Set diagnostic loclist")
nmap('<leader>/', [[:nohl<CR>]], "Clear search highlight")
nmap('<leader><', [[:call AdjustFontSize(-1)<CR>]], "Decrease font size")
nmap('<leader>>', [[:call AdjustFontSize(1)<CR>]], "Increase font size")
nmap('<leader>F', [[:let g:neovide_fullscreen=!g:neovide_fullscreen<CR>]], "Toggle fullscreen")
nmap('<leader>R', function() vim.cmd(string.format("source %s", os.getenv("MYVIMRC"))) end, "Reload config")
nmap('<leader>c', [[gg"+yG]], "Copy entire buffer to clipboard")
nmap('<leader>g', [[:LazyGit<CR>]], "Open LazyGit")
nmap('<leader>p', [["+p]], "Paste from clipboard")
nmap('<leader>w', [[<cmd>w<CR>]], "Write file")
nmap('<leader>m', [[<cmd>w<CR><cmd>make<CR>]], "Write and make")
nmap('<C-S-B>', [[<cmd>make<CR>]], "Make")
imap('<C-R>', [[<C-R><C-O>]], "Insert register")

nmap('<A-m>', [[<CMD>lua require('telescope.builtin').lsp_document_symbols()<CR>]], "LSP document symbols")
nmap('<A-s>', [[<CMD>lua require('telescope.builtin').lsp_dynamic_workspace_symbols({fname_width = 50})<CR>]], "LSP workspace symbols")
nmap('<leader>b', [[<CMD>lua require('telescope.builtin').buffers()<CR>]], "Find buffers")
nmap('<leader>f', [[<CMD>lua require('telescope.builtin').find_files()<CR>]], "Find files")
nmap('<leader>t', [[<CMD>lua require('telescope.builtin').treesitter()<CR>]], "Treesitter symbols")
nmap('<leader>z=', [[<CMD>lua require('telescope.builtin').spell_suggest()<CR>]], "Spell suggest")
nmap('<leader>d', [[<CMD>Telescope dap<CR>]], "DAP commands")
nmap('<leader>e', [[<CMD>Telescope file_browser<CR>]], "File browser")
nmap('<leader>h', [[<CMD>Telescope help_tags<CR>]], "Help tags")

nmap('<F4>', ":lua require'dap'.terminate()<CR>", "DAP: Terminate")
nmap('<F5>', ":lua require'init.dap'.continue_improved()<CR>", "DAP: Continue")
nmap('<F6>', ":lua require'dap'.pause(0)<CR>", "DAP: Pause")
nmap('<F7>', ":lua require'dap'.run_to_cursor()<CR>", "DAP: Run to cursor")
nmap('<F8>', ":lua require'dap'.set_breakpoint(vim.fn.input('Breakpoint condition: '))<CR>", "DAP: Set conditional breakpoint")
nmap('<F9>',    ":lua require'dap'.toggle_breakpoint()<CR>", "DAP: Toggle breakpoint")
nmap('<F10>',   ":lua require'dap'.step_over()<CR>", "DAP: Step over")
nmap('<F11>',   ":lua require'dap'.step_into()<CR>", "DAP: Step into")
nmap('<F12>',   ":lua require'dap'.step_out()<CR>", "DAP: Step out")
nmap('<leader>dp',   ":lua require'dap'.up()<CR>", "DAP: Up stack frame")
nmap('<leader>dn',   ":lua require'dap'.down()<CR>", "DAP: Down stack frame")
nmap('<leader>d0', [[:lua require'dapui'.toggle({layout=0})<CR>]], "DAP UI: Toggle layout 0")
nmap('<leader>d1', [[:lua require'dapui'.toggle({layout=1})<CR>]], "DAP UI: Toggle layout 1")
nmap('<leader>d2', [[:lua require'dapui'.toggle({layout=2})<CR>]], "DAP UI: Toggle layout 2")
nmap('<leader>d3', [[:lua require'dapui'.toggle({layout=3})<CR>]], "DAP UI: Toggle layout 3")
nmap('<leader>d4', [[:lua require'dapui'.toggle({layout=4})<CR>]], "DAP UI: Toggle layout 4")
nmap('<leader>d5', [[:lua require'dapui'.toggle({layout=5})<CR>]], "DAP UI: Toggle layout 5")
nmap('<leader>d6', [[:lua require'dapui'.toggle({layout=6})<CR>]], "DAP UI: Toggle layout 6")
nmap('<leader>d7', [[:lua require'dapui'.toggle({layout=7})<CR>]], "DAP UI: Toggle layout 7")
nmap('<leader>d8', [[:lua require'dapui'.toggle({layout=8})<CR>]], "DAP UI: Toggle layout 8")
nmap('<leader>d9', [[:lua require'dapui'.toggle({layout=9})<CR>]], "DAP UI: Toggle layout 9")
nmap('<leader>d0', [[:lua require'dapui'.close()<CR>]], "DAP UI: Close")
nmap('<leader>db', [[:lua require'dapui'.float_element("breakpoints")<CR>]], "DAP UI: Float breakpoints")
nmap('<leader>dh', [[:lua require'dapui'.float_element("hover")<CR>]], "DAP UI: Float hover")
nmap('<leader>dr', [[:lua require'dapui'.float_element("repl")<CR>]], "DAP UI: Float REPL")
nmap('<leader>dw', [[:lua require'dapui'.float_element("watches")<CR>]], "DAP UI: Float watches")
nmap('<leader>dww', [[:lua require'dapui'.float_element("watches")<CR>]], "DAP UI: Float watches")
nmap('<leader>dwa', [[:lua require'dapui'.elements.watches.add()<CR>]], "DAP UI: Add watch")
nmap('<leader>ds', [[:lua require'dapui'.float_element("stack")<CR>]], "DAP UI: Float stack")
nmap('<leader>di', [[:lua require'dapui'.float_element("scopes")<CR>]], "DAP UI: Float scopes")
nmap('<leader>dc', [[:lua require'dapui'.float_element("console")<CR>]], "DAP UI: Float console")

